### ISSUE TITLE
Expire Never defaults to 24 hours

### ISSUE THREAD

**Issue by r44v** [maximeplante/vscode-pastery#2]
Selecting **Never** creates a paste that expires in 24 hours, 

According to the developer the pastery api does not have an option for never expire. What may work is using the parameter duration: 26280000, this results in a paste of about 50 years.

The parameter duration: 0 results in an error.

**Comment by maximeplante** [comment]
I am not passing any duration parameter when the duration is equal to 0.
https://github.com/maximeplante/vscode-pastery/blob/70e96449cfd0c24c8b82aef3ada1785c4397decd/src/pastery.ts#L10-L21
I'm gonna take a look at it asap.

**Comment by maximeplante** [comment]
I wrote to the author of Pastery and there is no way of setting the expiration to **Never** in the api calls as of now. Somehow I thought my solution worked!

I used your solution in release `0.0.4`. Thanks a lot for pointing it out!

**Comment by r44v** [comment]
Works like a charm, Thanks
